export class BizConstants {
  static Category_Top10_Limit: number = 10
  static Category_TOP5_Limit: number = 5
  static SelectedIncomeCategoryIconBackColor: ResourceColor = Color.Green
  static SelectedOutComeCategoryIconBackColor: ResourceColor = $r("app.color.danger")
  static Max_Support_year = 2060
  static Min_Support_year = 2020
  static Max_Memo_char_count = 50
  static Max_Search_char_count = 20
  static MaxNumber = 100000000;
  static Month_reload_data_key = "Month_reload_data_key"
  static Report_reload_data_key = "Report_reload_data_key"
}