export interface CategoryItem {

  // 类型图片
  category_image: string
  // 类型名称
  category_name: string


}

export const DefaultOutcomeCategoryList: CategoryItem[] = [

  {
    // 类型图片
    category_image: "app.media.other_houses_48dp_F3F3F3",
    // 类型名称
    category_name: "其它"

  },
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "餐饮"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "购物"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "服饰"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "日用品"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "娱乐"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "食材"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "零食"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "烟酒茶"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "学习"
  }
]


export const DefaultIncomeCategoryList: CategoryItem[] = [

  {
    // 类型图片
    category_image: "app.media.other_houses_48dp_F3F3F3",
    // 类型名称
    category_name: "其它"

  },
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "薪资"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "奖金"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "借入"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "收债"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "利息"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "意外"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "兼职"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "礼金"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "股票"
  }
]

