export interface CategoryItem {

  // 类型图片
  category_image: string
  // 类型名称
  category_name: string


}

export const DefaultCategoryList: CategoryItem[] = [

  {
    // 类型图片
    category_image: "app.media.restaurant_48dp_F3F3F3",
    // 类型名称
    category_name: "餐饮"

  },
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
  ,
  {
    category_image: "app.media.flight_48dp_F3F3F3",
    category_name: "交通"
  }
]
